# Generated by Django 4.0.5 on 2022-06-15 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Buy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('toBuy', models.CharField(max_length=150)),
                ('dateStart', models.DateField(auto_now_add=True)),
                ('status', models.BooleanField(default=False)),
                ('dateEnd', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ToDo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('toDo', models.CharField(max_length=150)),
                ('dateStart', models.DateField(auto_now_add=True)),
                ('dateEnd', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
